name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libxt-dev libfontconfig1-dev pandoc

      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c("rsconnect", "shiny", "bslib", "DT", "dplyr", "readxl", "openxlsx", "tidyr", "rmarkdown", "shinyjs", "tinytex", "RColorBrewer"))'

      - name: Install TinyTeX
        run: |
          Rscript -e 'tinytex::install_tinytex(force = TRUE)'
          Rscript -e 'tinytex::tlmgr_install(c("booktabs", "colortbl", "xcolor", "float", "graphicx", "tikz", "fontspec", "amsmath", "oberdiek", "fancyvrb", "etoolbox"))'

      - name: Authorize and Deploy
        env:
          NAME: ${{ secrets.SHINYAPPS_NAME }}
          TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('NAME'), token=Sys.getenv('TOKEN'), secret=Sys.getenv('SECRET'))"
          Rscript -e "rsconnect::deployApp(appName='genomics-invoicing-app', appPrimaryDoc = 'TestApp.R', forceUpdate = TRUE)"
