name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2 

      - name: Restore renv environment
        run: renv::restore()
        shell: Rscript {0}

      - name: Install rsconnect
        run: install.packages('rsconnect')
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libxt-dev libfontconfig1-dev pandoc
          
      - name: Install TinyTeX
        run: |
          # Install TinyTeX only if it is missing to speed up deployment
          Rscript -e 'if(!tinytex::is_tinytex()) tinytex::install_tinytex()'
          # Install necessary LaTeX packages for the PDF invoice layout
          Rscript -e 'tinytex::tlmgr_install(c("booktabs", "colortbl", "xcolor", "float", "graphicx", "tikz", "helvet", "amsmath", "geometry", "fancyvrb", "etoolbox", "ragged2e"))'

      - name: Authorize and Deploy
        env:
          NAME: ${{ secrets.SHINYAPPS_NAME }}
          TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('NAME'), token=Sys.getenv('TOKEN'), secret=Sys.getenv('SECRET'))"
          # Deploy the application using TestApp.R as the primary file
          Rscript -e "rsconnect::deployApp(appName='genomics-invoicing-app', appPrimaryDoc = 'app.R', forceUpdate = TRUE)"
